# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJEZ4xRTUb2s6bHs9lD06AUn-scoKMC2
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score


# =======================
#      CONFIGURACIÓN
# =======================
st.set_page_config(page_title="Cluster de Pozos Petroleros", layout="wide")

st.title("🛢️ Dashboard Interactivo – Segmentación de Pozos Petroleros")
st.write("""
Aplicación diseñada para visualizar y analizar el comportamiento operativo
de pozos petroleros mediante **K-Means clustering**, PCA y centroides.
""")


# =======================
#   CARGA DE ARCHIVO
# =======================
st.sidebar.header("📂 Cargar archivo Excel")
uploaded_file = st.sidebar.file_uploader("Sube un archivo .xlsx o .xls", type=["xlsx", "xls"])

if uploaded_file is not None:

    # Cargar DataFrame
    df = pd.read_excel(uploaded_file)
    st.subheader("📋 Vista previa del dataset")
    st.dataframe(df.head())

    # VARIABLES DEL MODELO
    variables_modelo = [
        'Oil Prod.(bbl)','Water Prod.(bbl)','BS&W(%)','GOR(mscf/bbl)',
        'CHP(psig)','PD(psig)','Current (amp)','Choke(1/64 in)',
        'PIP(psig)','Nivel de Fluido(ft)','º API'
    ]
    variables_modelo = [v for v in variables_modelo if v in df.columns]

    # =======================
    #  PREPROCESAMIENTO
    # =======================
    df_model = df[variables_modelo].copy()
    df_model = df_model.fillna(df_model.median())

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(df_model)

    # =======================
    #         PCA
    # =======================
    pca_3 = PCA(n_components=3)
    X_pca3 = pca_3.fit_transform(X_scaled)

    df_pca = pd.DataFrame(X_pca3, columns=["PC1", "PC2", "PC3"])

    # =======================
    #       CLUSTERING
    # =======================
    st.sidebar.header("⚙️ Configuración del Clustering")
    k = st.sidebar.slider("Seleccione número de clusters (K)", 2, 10, value=5)

    model = KMeans(n_clusters=k, random_state=42, n_init=10)
    clusters = model.fit_predict(X_scaled)

    df["Cluster"] = clusters
    df_pca["Cluster"] = clusters

    # =======================
    #       MÉTRICAS
    # =======================
    sil = silhouette_score(X_scaled, clusters)
    db = davies_bouldin_score(X_scaled, clusters)

    st.sidebar.write("### 📊 Métricas del Modelo")
    st.sidebar.metric("Silhouette Score", f"{sil:.4f}")
    st.sidebar.metric("Davies–Bouldin Index", f"{db:.4f}")

    # =======================
    #   PCA 3D INTERACTIVO
    # =======================
    st.subheader("🌌 Visualización PCA – Clusters en 3D")

    import plotly.express as px
    fig = px.scatter_3d(
        df_pca,
        x="PC1", y="PC2", z="PC3",
        color=df_pca["Cluster"].astype(str),
        title="Clusters de Pozos (PCA 3D)",
        opacity=0.7
    )
    st.plotly_chart(fig, use_container_width=True)

    # =======================
    #     CENTROIDES
    # =======================
    st.subheader("📍 Centroides por Cluster")
    centroides = df.groupby("Cluster")[variables_modelo].mean()
    st.dataframe(centroides)

    # Heatmap de centroides
    st.subheader("🔥 Mapa de Calor de los Centroides")
    fig, ax = plt.subplots(figsize=(12, 6))
    sns.heatmap(centroides, annot=True, cmap="viridis", ax=ax)
    st.pyplot(fig)

    # =======================
    #    REGISTROS INDIVIDUALES
    # =======================
    st.subheader("🔎 Analizar un registro específico")
    idx = st.number_input("Seleccione un número de registro", 0, df.shape[0]-1, 0)
    st.write("Registro seleccionado:")
    st.dataframe(df.iloc[[idx]])

    st.write(f"➡ Este registro pertenece al **Cluster {df.loc[idx, 'Cluster']}**")

else:
    st.info("👈 Por favor cargue un archivo para comenzar.")
